
server:
  port: 9200

spring:
  datasource:
    url: jdbc:mysql://34.118.154.173:3306/kookbee_portfolio?serverTimezone=Asia/Seoul
    username: bee
    password: 1q2w3e4r
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  data:
    redis:
      host: 34.64.173.178
      port: 6379
  application:
    name: portfolio-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://34.64.69.238:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}