
server:
  port: 9200

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kookbee_portfolio?serverTimezone=Asia/Seoul
    username: root
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  data:
    mongodb:
      host: 35.205.7.177
      port: 27017
      database: note
      username: "bee"
      password: "q1w2e3r4!"
      authentication-database: admin
    redis:
      host: 35.205.7.177
      port: 6379
  application:
    name: portfolio-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}